[package]
name = "cargo_test"
version = "0.1.0"
authors = ["Administrator"]
edition = "2018"

[dependencies]
#rayon = "1.1.0"
#num-traits = "0.2.8"
#generic-array = "0.13.1"
#numeric-array = "0.3.1"
rand = "0.7.0"
